### ISSUE TITLE
panic: runtime error: integer divide by zero

### ISSUE THREAD

**Issue by iamlaobie** [cbeuw/GoQuiet#19]
Hi:
I run server like this
`ss-server -s 0.0.0.0 -p 6667 -k*** -m aes-256-cfb --plugin /opt/gq/gq-server --plugin-opts /opt/gq/gq-server.json`

run client like this:
`ss-local -s 172.105.198.92 -k*** -m aes-256-cfb -l 1089 -p 6667 --plugin /opt/gq/gq-client --plugin-opts "/opt/gq/gq.json"`

 run client and it echo 
```
 2018-03-22 21:56:17 INFO: plugin "/opt/gq/gq-client" enabled
 2018-03-22 21:56:17 INFO: initializing ciphers... aes-256-cfb
 2018-03-22 21:56:17 INFO: listening at 127.0.0.1:1089
```
when I use SwitchyOmega connect the local port 1089, the ss-client exit and echo 

```
panic: runtime error: integer divide by zero

goroutine 5 [running]:
github.com/cbeuw/GoQuiet/gqclient/TLS.makeSessionTicket(0xc4200820a0, 0x0, 0x0, 0x2)
	/home/andy/go/src/github.com/cbeuw/GoQuiet/gqclient/TLS/TLS.go:77 +0x12d
github.com/cbeuw/GoQuiet/gqclient/TLS.(*chrome).composeExtensions(0xc420044e58, 0xc4200820a0, 0xc4200123e0, 0x1c, 0x1c)
	/home/andy/go/src/github.com/cbeuw/GoQuiet/gqclient/TLS/chrome.go:38 +0x673
github.com/cbeuw/GoQuiet/gqclient/TLS.(*chrome).composeClientHello(0xc420044e58, 0xc4200820a0, 0x3, 0xc420012300, 0x13)
	/home/andy/go/src/github.com/cbeuw/GoQuiet/gqclient/TLS/chrome.go:71 +0x33f
github.com/cbeuw/GoQuiet/gqclient/TLS.ComposeInitHandshake(0xc4200820a0, 0x3, 0xc420012300, 0x13)
	/home/andy/go/src/github.com/cbeuw/GoQuiet/gqclient/TLS/TLS.go:103 +0x324
main.initSequence(0x121cc40, 0xc42000c050, 0xc4200820a0)
	/home/andy/GoQuiet/cmd/gq-client/gq-client.go:91 +0x1ed
created by main.main
	/home/andy/GoQuiet/cmd/gq-client/gq-client.go:184 +0x53f
 2018-03-22 21:58:55 ERROR: plugin service exit unexpectedly```

**Comment by cbeuw** [comment]
Hi,
This seems to be caused by `TicketTimeHint` not being set. Can you paste your gq-client config file here?
